spring.application.name=academy

# Use in-memory database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Esto crea las tablas automáticamente en la RAM
spring.jpa.hibernate.ddl-auto=update

# Default port for HTTPS
server.port=8443

# Configuración SSL
server.ssl.key-store=classpath:keystore.jks
server.ssl.key-store-password=rayokross123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=rayokross

#Mustache recognition on .html
spring.mustache.suffix=.html


#Activate this block when the app ends and delete the one above.
server.error.include-exception=false
server.error.include-stacktrace=never
server.error.include-message=never
logging.level.web=INFO



# Force UTF-8 encoding on the server and in Mustache

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.mustache.charset=UTF-8