spring.application.name=academy

# Usar base de datos en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Esto crea las tablas automáticamente en la RAM
spring.jpa.hibernate.ddl-auto=update

# Puerto por defecto para HTTPS
server.port=8443

# Configuración SSL
server.ssl.key-store=classpath:keystore.jks
server.ssl.key-store-password=rayokross123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=rayokross

#Reconocimiento del mustache sobre los .html
spring.mustache.suffix=.html

#Logger para ver información de las peticiones web
server.error.include-exception=true
server.error.include-stacktrace=always
logging.level.web=TRACE

# Forzar codificación UTF-8 en el servidor y en Mustache
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.mustache.charset=UTF-8