spring.application.name=academy

# Usar base de datos en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Esto crea las tablas automáticamente en la RAM
spring.jpa.hibernate.ddl-auto=update
# Configuración HTTPS
server.port=8443
server.ssl.key-store=classpath:keystore.jks
server.ssl.key-store-password=password
server.ssl.key-password=secret

#Reconocimiento del mustache sobre los .html
spring.mustache.suffix=.html
